-- SQLite
INSERT INTO post (id,
  title,
  price,
  category,
  state,
  type,
  option,
  description,
  path,
  groups,
  label
)
VALUES
  (1,
    'Espejo Decorativo Pared Hogar',
    150,
    'Muebles',
    'Nuevo',
    '',
    '',
    'Elegante espejo decorativo para la pared de tu hogar.',
    'espejo_decorativo_pared',
    '',
    ''
  ),
  (2,
    'Cortina Opaca para Ventanas',
    50,
    'Varios',
    'Nuevo',
    '',
    '',
    'Cortina opaca ideal para ventanas, bloquea la luz solar.',
    'cortina_opaca_ventanas',
    '',
    ''
  ),
  (3,
    'Juego de Ollas Antiadherentes',
    200,
    'Hogar',
    'Nuevo',
    '',
    '',
    'Juego de ollas antiadherentes de alta calidad para tu cocina.',
    'juego_ollas_antiadherentes',
    '',
    ''
  ),
  (4,
    'Set de Vasos de Vidrio',
    30,
    'Varios',
    'Nuevo',
    '',
    '',
    'Set de vasos de vidrio para tus bebidas favoritas.',
    'set_vasos_vidrio',
    '',
    ''
  ),
  (5,
    'Licuadora Multifuncional',
    120,
    'Electrodomésticos',
    'Nuevo',
    '',
    '',
    'Licuadora multifuncional con varias velocidades y funciones.',
    'licuadora_multifuncional',
    '',
    ''
  ),
  (6, 'Bolsa De Agua Caliente Eléctrica Invierno Calentador',
  70,
  'Hogar',
  'Nuevo',
  '',
  '',
  'Util Bolsa De Agua Caliente Eléctrica Invierno Calentador Vacias.',
  'Bolsa calentadora agua',
  '',
  ''
  );